---
- name: copy httpd configuration
  copy: src=files/httpd.original dest=/etc/httpd/conf/httpd.conf
- name: copy index.html file
  copy: src=files/index.html dest=/var/www/html
  notify:
    - restart apache
